"""table

Revision ID: 79e911e442af
Revises: 
Create Date: 2019-07-04 17:42:38.566804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e911e442af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_e7db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalyst',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delete', sa.Integer(), nullable=True),
    sa.Column('catalyst', sa.String(length=16), nullable=True),
    sa.Column('qbaddr1', sa.String(length=64), nullable=True),
    sa.Column('webaddr2', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constellation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delete', sa.Integer(), nullable=True),
    sa.Column('constellation', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delete', sa.Integer(), nullable=True),
    sa.Column('heroname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delete', sa.Integer(), nullable=True),
    sa.Column('shop', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalyst_shops',
    sa.Column('catalyst_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalyst_id'], ['catalyst.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], )
    )
    op.create_table('constellation_catalysts',
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.Column('catalyst_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalyst_id'], ['catalyst.id'], ),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellation.id'], )
    )
    op.create_table('hero_constellations',
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellation.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], )
    )
    op.create_table('nicename',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delete', sa.Integer(), nullable=True),
    sa.Column('nicename', sa.String(length=64), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_e7db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nicename')
    op.drop_table('hero_constellations')
    op.drop_table('constellation_catalysts')
    op.drop_table('catalyst_shops')
    op.drop_table('shop')
    op.drop_table('hero')
    op.drop_table('constellation')
    op.drop_table('catalyst')
    # ### end Alembic commands ###


def upgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delete', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=36), nullable=True),
    sa.Column('_password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_user():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    # ### end Alembic commands ###

